name: Claude PR Assistant

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  claude_pr_assistant:
    if: contains(github.event.comment.body, '@claude') || contains(github.event.issue.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    timeout-minutes: 60
    steps:
      - name: Run Claude Code Action
        uses: anthropics/claude-code-action@main
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional: Enable experimental network domain restrictions
          # allowed_domains: "api.github.com,github.com"